---
- name: "Create L2 segments on BCF"
  hosts: bcf
  gather_facts: false
  vars_files:
    - vars/segment_vars.yml

  tasks:
    - name: configure mode BCF
      cli_command:
        command: enable
        sendonly: yes

    - name: build L2 segments
      cli_config:
        config: "tenant {{ item.0.tenant_name }}; segment vlan{{ item.0.vlan }}; member interface-group {{ item.1 }} vlan {{ item.0.vlan }};"
      loop: "{{ segments | subelements('interface_groups', 'skip_missing=True') }}"
