---
- name: "Move L3 from nexus to BCF"
  hosts: lab
  gather_facts: false
  vars_files:
    - vars/segment_vars.yml

  tasks:
    - name: enable mode
      cli_command:
        command: enable
        sendonly: yes
      when: device_group == 'bcf'

    - name: build L3 segments on BCF
      cli_config:
        config: "tenant {{ item.tenant_name }}; logical-router; interface segment vlan{{ item.vlan }}; ip address {{ item.ip }};"
      loop: "{{ segments }}"
      when: device_group == 'bcf'

    - name: 'shutdown nexus vlan interface'
      nxos_interface:
        name: Vlan{{ item.vlan }}
        admin_state: down
      loop: "{{ segments }}"
      when: device_group == 'lab-nexus-rtrs'

    - name: save config
      nxos_config:
        save_when: modified
      when: device_group == 'lab-nexus-rtrs'
